/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': '#8083ff',
        'on-primary-fixed': '#07006c',
        'secondary-fixed': '#d8e3fb',
        'surface-dim': '#13131b',
        'primary-fixed-dim': '#c0c1ff',
        'secondary-container': '#3e495d',
        'inverse-on-surface': '#303038',
        'surface-bright': '#393841',
        'secondary': '#bcc7de',
        'on-error': '#690005',
        'tertiary-container': '#d97721',
        'tertiary-fixed-dim': '#ffb783',
        'on-primary-container': '#0d0096',
        'on-tertiary-container': '#452000',
        'secondary-fixed-dim': '#bcc7de',
        'on-primary-fixed-variant': '#2f2ebe',
        'surface': '#13131b',
        'inverse-primary': '#494bd6',
        'on-secondary': '#263143',
        'surface-tint': '#c0c1ff',
        'on-tertiary-fixed': '#301400',
        'error': '#ffb4ab',
        'surface-container-high': '#292932',
        'outline-variant': '#464554',
        'tertiary-fixed': '#ffdcc5',
        'on-background': '#e4e1ed',
        'on-secondary-fixed-variant': '#3c475a',
        'on-tertiary-fixed-variant': '#703700',
        'surface-variant': '#34343d',
        'surface-container-lowest': '#0d0d15',
        'on-error-container': '#ffdad6',
        'on-surface-variant': '#c7c4d7',
        'on-secondary-container': '#aeb9d0',
        'surface-container': '#1f1f27',
        'primary-fixed': '#e1e0ff',
        'outline': '#908fa0',
        'inverse-surface': '#e4e1ed',
        'primary': '#c0c1ff',
        'on-surface': '#e4e1ed',
        'on-tertiary': '#4f2500',
        'error-container': '#93000a',
        'tertiary': '#ffb783',
        'on-primary': '#1000a9',
        'on-secondary-fixed': '#111c2d',
        'surface-container-highest': '#34343d',
        'surface-container-low': '#1b1b23',
        'background': '#13131b',
        'on-error-container': '#ffdad6',
        'on-surface-variant': '#c7c4d7',
        'surface-variant': '#34343d',
        'surface-container': '#1f1f27',
      },
      fontFamily: {
        'body-md': ['Manrope', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'button': ['Inter', 'sans-serif'],
        'headline': ['Inter', 'sans-serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'pulse-soft': 'pulseSoft 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '.8' },
        },
      },
    },
  },
  plugins: [],
}
